package com.zerobase.appointment.type;

public enum AlarmType {
  FRIEND_REQUEST_ACCEPTED,
  APPOINTMENT_CONFIRMED,
  APPOINTMENT_CHANGED,
  APPOINTMENT_CANCELED,
  APPOINTMENT_NOTI,
  APPOINTMENT_REQUEST_STATUS_RESULT
}
